site_name: Pyre-Bot
nav:
    - Home: index.md
    - About:
      - 'License': 'LICENSE.md'
      - 'Changelog': 'CHANGELOG.md'
theme: readthedocs
repo_url: https://github.com/InfernalPlacebo/pyre-bot
