site_name: Pyre-Bot
nav:
  - Home: index.md
  - About:
      - 'License': 'LICENSE.md'
      - 'Changelog': 'CHANGELOG.md'
  - BotCommands:
      - 'BotCommands': 'BotCommands/botcommands.md'
      - 'Changelog': 'BotCommands/CHANGELOG.md'
theme: readthedocs
repo_url: https://github.com/InfernalPlacebo/pyre-bot
